repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: end-of-file-fixer
    files: \.py$
  - id: trailing-whitespace
    files: \.py$
- repo: https://github.com/psf/black
  rev: 19.3b0
  hooks:
  - id: black
    files: \.py$
- repo: https://github.com/asottile/seed-isort-config
  rev: v1.9.4
  hooks:
  - id: seed-isort-config
    files: \.py$
- repo: https://github.com/pre-commit/mirrors-isort
  rev: v4.3.21
  hooks:
  - id: isort
    files: \.py$