version: '3'
services:
  api_1:
    build: .
    expose:
      - "3000"
    volumes:
      - ./src:/usr/app/src
  api_2:
    build: .
    expose:
      - "3000"
    volumes:
      - ./src:/usr/app/src
  api_3:
    build: .
    expose:
      - "3000"
    volumes:
      - ./src:/usr/app/src

  webserver:
    image: nginx:latest
    links:
      - api_1
      - api_2
      - api_3
    ports:
      - "8080:80"
    volumes:
      - ./deploy/local/nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - ./deploy/local/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/logs/nginx
