web:
  build: .
  ports:
    - "8888:5000"
  links:
    - postgres:postgres
  command: uwsgi --ini random-api.ini

data:
  restart: always
  image: postgres:latest
  volumes:
    - ./init/init.sql:/docker-entrypoint-initdb.d/init.sql
    - /var/lib/postgresql
  command: "true"

postgres:
  restart: always
  image: postgres:9.3
  volumes_from:
    - data
  ports:
    - "5434:5432"